default: ./Driver/DoubleQueueDriver.java ./com/gradescope/DoubleQueue/code/IDoubleQueue.java ./com/gradescope/DoubleQueue/code/ArrayDoubleQueue.java ./com/gradescope/DoubleQueue/code/ListDoubleQueue.java 
	javac ./com/gradescope/DoubleQueue/code/IDoubleQueue.java ./com/gradescope/DoubleQueue/code/ArrayDoubleQueue.java ./com/gradescope/DoubleQueue/code/ListDoubleQueue.java ./Driver/DoubleQueueDriver.java

run:
	java Driver.DoubleQueueDriver

clean:
	rm *.class